// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufkaboevabmyqbfdkhet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVma2Fib2V2YWJteXFiZmRraGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODYyNDUsImV4cCI6MjA1ODQ2MjI0NX0.PV4R7AvrIAMFPJpMq4PC-5i27C5nVcjVMx-5B9Gg5w4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);